### ISSUE TITLE
Request for Second Seminar of Developer Team

### ISSUE THREAD

**Issue by DawsenSu** [DawsenSu/PDIWT_PiledWharf#2]
- **Subjcet:** Technicals of interoperating between C++/C##
- **Speaker:**  @CuiFeng 
- **Time:** Schuduled for Thursday, 2018-07-11, 8:30.
- **Location:** Jianxiang Office.
- **Duration:** Approximately 1.5 hours.
- **It's better to give some examples for every method including, but not limited to P/Invoke, Marshal, and C++/CLI.**

_Next Seminar topic:  MVVM design pattern in WPF_

**Comment by runehacker** [comment]
Roger...

**Comment by DawsenSu** [comment]
Good start!
@afas2005 Please sort your tutorial code and share it.

**Comment by afas2005** [comment]
I will format and commit the code as example shown today

**Comment by runehacker** [comment]
You need an invitation from afas to access the code

**Comment by afas2005** [comment]
@runehacker The code shared to you is very messy, so I will push a new clear repository for comprehending
